import React, { useState } from 'react';
import { 
  Send, 
  Sparkles, 
  Mail, 
  Linkedin, 
  Globe, 
  Search, 
  Share2, 
  CheckCircle2,
  Copy,
  BarChart3
} from 'lucide-react';
import { useWorkspace } from '../../context/WorkspaceContext';

export const CampaignStudioView: React.FC = () => {
  const { campaigns, activeProduct, dispatchAgentAction, isDispatching, createCampaign } = useWorkspace();

  const [campaignName, setCampaignName] = useState<string>('Strategic Buyer Outreach Q3');
  const [channel, setChannel] = useState<'Email' | 'LinkedIn' | 'SEO' | 'Social' | 'PPC'>('Email');
  const [targetRole, setTargetRole] = useState<string>('CTO / VP of Engineering');
  const [generatedCopy, setGeneratedCopy] = useState<string>('');
  const [copied, setCopied] = useState<boolean>(false);

  const handleGenerateCampaign = async () => {
    const agentRoleToCall = channel === 'Email' ? 'EMAIL_OUTREACH' : channel === 'LinkedIn' ? 'SOCIAL_MARKETER' : 'SALES_COPYWRITER';
    
    const result = await dispatchAgentAction(
      agentRoleToCall,
      `Generate ${channel} Pitch Sequence`,
      `Generate high-converting 5-step ${channel} outreach pitch sequence targeting ${targetRole} for asset "${activeProduct?.name || 'CloudPulse APM'}". Target price: $${activeProduct?.askingPrice || 2450000}.`
    );

    setGeneratedCopy(result.response);

    // Save to campaigns list
    createCampaign({
      productId: activeProduct?.id || 'prod-saas-101',
      name: campaignName,
      channel,
      status: 'active',
      agentRoles: [agentRoleToCall, 'SALES_COPYWRITER', 'LEAD_QUALIFIER'],
      leadsTargeted: 120,
      openRate: 68.5,
      clickRate: 31.0,
      replyRate: 22.4,
      convertedDeals: 2,
      budgetSpent: 500,
      pipelineGenerated: 2450000,
      copyVariant: `5-Step ${channel} Cadence generated by ${agentRoleToCall}`
    });
  };

  const handleCopyText = () => {
    if (!generatedCopy) return;
    navigator.clipboard.writeText(generatedCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="p-4 lg:p-8 space-y-6 max-w-7xl mx-auto">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-slate-900 p-6 rounded-2xl border border-slate-800 shadow-xl">
        <div className="space-y-1">
          <div className="flex items-center space-x-2">
            <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold tracking-wider uppercase bg-amber-500/10 text-amber-400 border border-amber-500/30">
              Omnichannel Sales Marketing
            </span>
            <span className="text-slate-500">•</span>
            <span className="text-xs text-slate-400 font-mono">{activeProduct ? activeProduct.name : 'All Products'}</span>
          </div>
          <h1 className="text-2xl font-extrabold text-white tracking-tight">
            AI Campaign & Pitch Copywriter Studio
          </h1>
          <p className="text-xs text-slate-400">
            Copycraft AI, Outreach Commander, and Omni Social Agents generating cold outreach, pitch decks, and SEO content.
          </p>
        </div>

        <button
          onClick={handleGenerateCampaign}
          disabled={isDispatching}
          className="flex items-center space-x-2 px-4 py-2.5 bg-gradient-to-r from-amber-600 to-orange-600 hover:from-amber-500 hover:to-orange-500 text-white rounded-xl text-xs font-bold shadow-lg shadow-amber-600/20 active:scale-95 transition-all disabled:opacity-50 shrink-0"
        >
          <Sparkles className={`w-4 h-4 ${isDispatching ? 'animate-spin' : ''}`} />
          <span>{isDispatching ? 'Generating Copy...' : 'Generate Campaign Pitch'}</span>
        </button>
      </div>

      {/* Campaign Controls & Live Copy Output Split */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Col (5 cols): Generator Controls */}
        <div className="lg:col-span-5 bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4 shadow-xl">
          <h3 className="font-bold text-white text-sm pb-2 border-b border-slate-800">
            Campaign Setup & Strategy Config
          </h3>

          <div className="space-y-3">
            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-slate-300">Campaign Title</label>
              <input
                type="text"
                value={campaignName}
                onChange={(e) => setCampaignName(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3 text-xs text-slate-100 focus:outline-none focus:border-amber-500"
              />
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-slate-300">Outreach Channel</label>
              <select
                value={channel}
                onChange={(e) => setChannel(e.target.value as any)}
                className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3 text-xs text-slate-100 focus:outline-none focus:border-amber-500"
              >
                <option value="Email">Cold Email Sequence (Outreach Commander)</option>
                <option value="LinkedIn">LinkedIn Social Selling (Omni Social)</option>
                <option value="SEO">Programmatic SEO Page (Apex SEO)</option>
                <option value="Social">Twitter/X Founder Breakdown Thread</option>
                <option value="PPC">Google Search Ads & InMail Strategy</option>
              </select>
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-slate-300">Target Buyer Persona / Role</label>
              <input
                type="text"
                value={targetRole}
                onChange={(e) => setTargetRole(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3 text-xs text-slate-100 focus:outline-none focus:border-amber-500"
              />
            </div>
          </div>
        </div>

        {/* Right Col (7 cols): Generated Pitch Sequence */}
        <div className="lg:col-span-7 bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4 shadow-xl flex flex-col justify-between">
          <div className="space-y-3">
            <div className="flex items-center justify-between pb-2 border-b border-slate-800">
              <div className="flex items-center space-x-2">
                <Send className="w-4 h-4 text-amber-400" />
                <h3 className="font-bold text-white text-sm">Generated Pitch & Copy Assets</h3>
              </div>
              
              {generatedCopy && (
                <button
                  onClick={handleCopyText}
                  className="flex items-center space-x-1 px-3 py-1 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-semibold transition-colors"
                >
                  <Copy className="w-3.5 h-3.5 text-cyan-400" />
                  <span>{copied ? 'Copied!' : 'Copy Assets'}</span>
                </button>
              )}
            </div>

            <div className="bg-slate-950 border border-slate-800/80 rounded-xl p-4 text-xs font-sans text-slate-200 leading-relaxed max-h-[420px] overflow-y-auto custom-scrollbar whitespace-pre-wrap">
              {generatedCopy || (
                <div className="text-slate-500 italic text-center py-12">
                  Click &quot;Generate Campaign Pitch&quot; to invoke Copycraft AI and generate high-conversion outreach sequences.
                </div>
              )}
            </div>
          </div>
        </div>

      </div>

    </div>
  );
};
